2018-01-10 10:06:44.021 [error] <0.227.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.232.0> exit with reason normal in context child_terminated
2018-01-10 10:13:05.942 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-10 10:13:05.974 [error] <0.231.0> Supervisor 'Elixir.Zombieserver' had child 'Elixir.Zombieserver.Data' started with 'Elixir.Zombieserver.Data':start_link() at undefined exit with reason {'EXIT',{function_clause,[{'Elixir.Zombieserver.Data','-load_zombies/1-fun-0-',[{<<"location">>,#{<<"latitude">> => 407838351,<<"longitude">> => -746143763}}],[{file,"lib/data.ex"},{line,16}]},{'Elixir.Enum','-map/2-fun-0-',3,[{file,"lib/enum.ex"},{line,1274}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{'Elixir.Enum',map,2,[{file,"lib/enum.ex"},{line,1843}]},{'Elixir.Zombieserver.Data',start_link,0,[{file,"lib/data.ex"},{line,5}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},...]},...]}} in context start_error
2018-01-10 10:13:05.975 [error] <0.229.0> CRASH REPORT Process <0.229.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Zombieserver.Data',{'EXIT',{function_clause,[{'Elixir.Zombieserver.Data','-load_zombies/1-fun-0-',[{<<"location">>,#{<<"latitude">> => 407838351,<<"longitude">> => -746143763}}],[{file,"lib/data.ex"},{line,16}]},{'Elixir.Enum','-map/2-fun-0-',3,[{file,"lib/enum.ex"},{line,1274}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{'Elixir.Enum',map,2,[{file,"lib/enum.ex"},{line,1843}]},{'Elixir.Zombieserver.Data',start_link,0,[{file,"lib/data.ex"},{line,...}]},...]}}}},...} in application_master:init/4 line 134
2018-01-10 10:16:20.728 [error] <0.167.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.172.0> exit with reason normal in context child_terminated
2018-01-14 12:21:37.100 [error] <0.237.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.242.0> exit with reason normal in context child_terminated
2018-01-14 12:55:46.072 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-14 12:57:09.610 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-14 12:59:48.277 [error] <0.167.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.172.0> exit with reason normal in context child_terminated
