2018-01-14 12:37:43.151 [error] <0.237.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.242.0> exit with reason normal in context child_terminated
2018-01-14 12:37:43.199 [error] <0.293.0> Supervisor 'Elixir.Zombieclient' had child 'Elixir.Zombieclient.Consumer' started with 'Elixir.Zombieclient.Consumer':start_link(#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sam...">>},...]}) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Zombieclient.Consumer',start_link,[#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/zombieclient.crt">>},{keyfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/zombieclient.key">>},{cacertfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/Zombie_Spotters_Ltd.cert">>},{secure_renegotiate,true},{reuse_sessions,true},{verify,verify_peer},...]}],...},...]}} in context start_error
2018-01-14 12:37:43.199 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Zombieclient.Consumer',{'EXIT',{undef,[{'Elixir.Zombieclient.Consumer',start_link,[#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/zombieclient.crt">>},{keyfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/zombieclient.key">>},{cacertfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/Zombie_Spotters_Ltd.cert">>},...]}],...},...]}}}},...} in application_master:init/4 line 134
2018-01-14 12:38:17.429 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-14 12:38:17.466 [error] <0.231.0> Supervisor 'Elixir.Zombieclient' had child 'Elixir.Zombieclient.Consumer' started with 'Elixir.Zombieclient.Consumer':start_link(#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sam...">>},...]}) at undefined exit with reason ok in context start_error
2018-01-14 12:38:17.466 [error] <0.229.0> CRASH REPORT Process <0.229.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Zombieclient.Consumer',ok}},{'Elixir.Zombieclient.App',start,[normal,[]]}} in application_master:init/4 line 134
2018-01-14 12:40:34.541 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-14 12:40:34.576 [error] <0.231.0> Supervisor 'Elixir.Zombieclient' had child 'Elixir.Zombieclient.Consumer' started with 'Elixir.Zombieclient.Consumer':start_link(#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sam...">>},...]}) at undefined exit with reason ok in context start_error
2018-01-14 12:40:34.576 [error] <0.229.0> CRASH REPORT Process <0.229.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Zombieclient.Consumer',ok}},{'Elixir.Zombieclient.App',start,[normal,[]]}} in application_master:init/4 line 134
2018-01-14 12:42:53.368 [error] <0.176.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.181.0> exit with reason normal in context child_terminated
2018-01-14 12:42:53.414 [error] <0.230.0> CRASH REPORT Process <0.230.0> with 0 neighbours exited with reason: bad return value ok from 'Elixir.Zombieclient.App':start(normal, []) in application_master:init/4 line 134
2018-01-14 12:43:38.193 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-14 12:43:38.225 [error] <0.229.0> CRASH REPORT Process <0.229.0> with 0 neighbours exited with reason: bad return value {ok} from 'Elixir.Zombieclient.App':start(normal, []) in application_master:init/4 line 134
2018-01-14 12:46:25.541 [error] <0.182.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.187.0> exit with reason normal in context child_terminated
2018-01-14 12:46:25.581 [error] <0.238.0> Supervisor 'Elixir.Routeguide' had child 'Elixir.Zombieclient.Consumer' started with 'Elixir.Zombieclient.Consumer':start_link(#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sam...">>},...]}) at undefined exit with reason {'EXIT',{undef,[{'Elixir.Zombieclient.Consumer',start_link,[#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/zombieclient.crt">>},{keyfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/zombieclient.key">>},{cacertfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/Zombie_Spotters_Ltd.cert">>},{secure_renegotiate,true},{reuse_sessions,true},{verify,verify_peer},...]}],...},...]}} in context start_error
2018-01-14 12:46:25.582 [error] <0.236.0> CRASH REPORT Process <0.236.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Zombieclient.Consumer',{'EXIT',{undef,[{'Elixir.Zombieclient.Consumer',start_link,[#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/zombieclient.crt">>},{keyfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/zombieclient.key">>},{cacertfile,<<"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/Zombie_Spotters_Ltd.cert">>},...]}],...},...]}}}},...} in application_master:init/4 line 134
2018-01-14 12:46:45.846 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-14 12:55:07.895 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-14 12:55:07.985 [error] <0.232.0> CRASH REPORT Process <0.232.0> with 0 neighbours exited with reason: econnrefused in gen_fsm:init_it/6 line 358
2018-01-14 12:55:07.985 [error] <0.231.0> Supervisor 'Elixir.Routeguide' had child 'Elixir.Zombieclient.Consumer' started with 'Elixir.Zombieclient.Consumer':start_link(#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sam...">>},...]}) at undefined exit with reason {'EXIT',{{badmatch,{error,econnrefused}},[{'Elixir.GRPC.Channel',connect,3,[{file,"lib/grpc/channel.ex"},{line,46}]},{'Elixir.Zombieclient.Consumer',start_link,1,[{file,"lib/consumer.ex"},{line,6}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_se..."},...]},...]}} in context start_error
2018-01-14 12:55:07.985 [error] <0.229.0> CRASH REPORT Process <0.229.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Zombieclient.Consumer',{'EXIT',{{badmatch,{error,econnrefused}},[{'Elixir.GRPC.Channel',connect,3,[{file,"lib/grpc/channel.ex"},{line,46}]},{'Elixir.Zombieclient.Consumer',start_link,1,[{file,"lib/consumer.ex"},{line,6}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"..."},...]},...]}}}},...} in application_master:init/4 line 134
2018-01-14 12:55:55.239 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.169.0> exit with reason normal in context child_terminated
2018-01-14 12:55:55.352 [error] <0.221.0> CRASH REPORT Process <0.221.0> with 0 neighbours exited with reason: {options,{cacertfile,"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/Zombie_Spotters_Ltd.cert",{error,enoent}}} in gen_fsm:init_it/6 line 358
2018-01-14 12:55:55.352 [error] <0.220.0> Supervisor 'Elixir.Routeguide' had child 'Elixir.Zombieclient.Consumer' started with 'Elixir.Zombieclient.Consumer':start_link(#{'__struct__' => 'Elixir.GRPC.Credential',ssl => [{certfile,<<"/Users/zxm170/elixir/grpctls_sam...">>},...]}) at undefined exit with reason {'EXIT',{{badmatch,{error,{options,{cacertfile,"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/Zombie_Spotters_Ltd.cert",{error,enoent}}}}},[{'Elixir.GRPC.Channel',connect,3,[{file,"lib/grpc/channel.ex"},{line,46}]},{'Elixir.Zombieclient.Consumer',start_link,1,[{file,"lib/consumer.ex"},{line,6}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"super..."},...]},...]}} in context start_error
2018-01-14 12:55:55.352 [error] <0.218.0> CRASH REPORT Process <0.218.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Zombieclient.Consumer',{'EXIT',{{badmatch,{error,{options,{cacertfile,"/Users/zxm170/elixir/grpctls_sample/_build/dev/lib/zombieclient/priv/Zombie_Spotters_Ltd.cert",{error,enoent}}}}},[{'Elixir.GRPC.Channel',connect,3,[{file,"lib/grpc/channel.ex"},{line,46}]},{'Elixir.Zombieclient.Consumer',start_link,1,[{file,"lib/consumer.ex"},{line,6}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"super..."},...]},...]}}}},...} in application_master:init/4 line 134
2018-01-14 12:57:19.874 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
2018-01-14 12:59:53.969 [error] <0.175.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.180.0> exit with reason normal in context child_terminated
